# Config file for automatic testing at travis-ci.org

language: python
addons:
    postgresql: "9.3"

install: pip install tox coveralls

before_script:
    - psql -U postgres -c 'create database bpzaroundme;'
    - psql -U postgres -c 'create extension if not exists postgis;'

script: tox
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=style
    - TOXENV=docs

after_success: coveralls
